### ISSUE TITLE
Exception:  No hmac found for property "type" 

### ISSUE THREAD

**Issue by saherch** [maikschneider/bw_captcha#17]
I am trying to use this extension with typo3 version 11.5.16. I am using the latest version 2.0.4.

While adding a Captcha element to a form and trying to save it, i get the following exception.

Exception while property mapping at property path "": No hmac found for property "type" (form element "captcha-1").

In my log file,  the following is logged:
[CRITICAL] request="66b34644ce7ac" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Extbase\Property\Exception, code #1297759968, file C:\htdocs\stage03\public\typo3\sysext\extbase\Classes\Property\PropertyMapper.php, line 122: Exception while property mapping at property path "": No hmac found for property "type" (form element "captcha-1") #1528588037 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Extbase\\Property\\Exception","exception_code":1297759968,"file":"C:\\htdocs\\stage03\\public\\typo3\\sysext\\extbase\\Classes\\Property\\PropertyMapper.php","line":122,"message":"Exception while property mapping at property path \"\": No hmac found for property \"type\" (form element \"captcha-1\") #1528588037","request_url":"https://localhost/stage03/public/typo3/module/web/FormFormbuilder?token=--AnonymizedToken--&tx_form_web_formformbuilder%5Baction%5D=saveForm&tx_form_web_formformbuilder%5Bcontroller%5D=FormEditor","exception":null}

**Comment by maikschneider** [comment]
Hi @saherch, sorry for the late response. Could you resolve your issue?

It's been a long time since I encountered this error. It sounds quite similar to [this issue](https://github.com/evoWeb/recaptcha/issues/39) of the recaptcha element. 

Is the form / captcha working in the frontend? Does your form.yaml look like this:

```
      -
        type: Captcha
        identifier: captcha-1
        label: Captcha
        properties:
          fluidAdditionalAttributes:
            required: required
          validators:
            - identifier: NotEmpty
```

If the form is not working, try to remove the validator `NotEmpty`, like the guys at repatcha did.

**Comment by saherch** [comment]
Hi @maikschneider, 
I am still unable to solve my problem. 
Coincidentally, i have the same error with the 'recaptcha' extension. 
When I make a basic form with name and email fields, it is saved and displayed in the front-end.
The problem with this extension (and also with re-captcha) is that i am unable to save my form when i try to add a 'captcha' form element. Hence my form.yaml has no identifier with name captcha. Below is how my current form.yaml looks like:

```

renderingOptions:
  submitButtonLabel: Submit
type: Form
identifier: contactform
label: 'Contact form'
prototypeName: standard
finishers:
  -
    options:
      pageUid: '44'
      additionalParameters: ''
    identifier: Redirect
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    type: Page
    identifier: page-1
    label: Step
    renderables:
      -
        defaultValue: ''
        type: Text
        identifier: text-1
        label: 'First Name'
        properties:
          fluidAdditionalAttributes:
            required: required
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: ''
        type: Text
        identifier: text-2
        label: 'Last Name'
      -
        defaultValue: ''
        type: Email
        identifier: email-1
        label: 'Email address'
        validators:
          -
            identifier: EmailAddress

```
