### ISSUE TITLE
Frontend leads to UnknownElement.html

### ISSUE THREAD

**Issue by akroii** [maikschneider/bw_captcha#36]
Hi,
i'm using bw_captcha 3.0.1 and the Captcha doesn't appear in frontend. In my fluid debug view its only wrapped by UnknownElement.html

bw_captcha is installed and works properly only lokally. On server it remains empty.

FormSetup.Yaml
```
TYPO3:
  CMS:
    Form:
      persistenceManager:
        allowedExtensionPaths:
          1591099959: EXT:xxx/Resources/Private/Extensions/Form/
        allowSaveToExtensionPaths: true
        allowDeleteFromExtensionPaths: false
      prototypes:
        standard:
          formElementsDefinition:
            Form:
              renderingOptions:
                templateRootPaths:
                  70: 'EXT:xxx/Resources/Private/Extensions/Form/Templates/'
                partialRootPaths:
                  1690380901: 'EXT:xxx/Resources/Private/Extensions/Form/Partials/'
```
Do you have any Ideas?

T3 11.5.29
