### ISSUE TITLE
Missing input class in v12

### ISSUE THREAD

**Issue by maikschneider** [maikschneider/bw_captcha#39]
In TYPO3 v12.4.5 the html class `is-invalid` is missing after submitting a wrong captcha. When using the bootstrap package, this causes the input to be not marked red and the error message therefore isn't shown as well.

**Comment by maikschneider** [comment]
This is due to a template variant in the form extension:

```
prototypes:
  standard:
    formElementsDefinition:
      Form:
       [...]
        variants:
          -
            identifier: template-variant
            condition: 'getRootFormProperty("renderingOptions.templateVariant") == "version2"'
            renderingOptions:
              templateRootPaths:
                10: 'EXT:form/Resources/Private/FrontendVersion2/Templates/'
              partialRootPaths:
                10: 'EXT:form/Resources/Private/FrontendVersion2/Partials/'
              layoutRootPaths:
                10: 'EXT:form/Resources/Private/FrontendVersion2/Layouts/'
              fieldProperties:
                errorMsgClassAttribute: invalid-feedback
                errorClassAttribute: is-invalid
                descriptionClassAttribute: form-text
                requiredMarkClassAttribute: required
                visuallyHiddenClassAttribute: visually-hidden
              formNavigation:
                navigationWrapperClassAttribute: actions
                navigationClassAttribute: form-navigation
                navigationAriaLabelAttribute: Form Navigation
                btnPreviousClassAttribute: 'btn btn-outline-primary'
                btnNextClassAttribute: 'btn btn-primary'
                btnSubmitClassAttribute: 'btn btn-primary'
```
The captcha element definition could be extended to support this variant.
